-- Oracle DDL Script for Stage 3.6 Historical Regime Engine Tables

CREATE TABLE STAGING.MARKET_REGIMES (
    DATETIME               DATE NOT NULL,
    REGIME_NAME            VARCHAR2(30) NOT NULL,
    PCT_ABOVE_EMA20        NUMBER(6,2),
    PCT_ABOVE_EMA50        NUMBER(6,2),
    PCT_ABOVE_EMA200       NUMBER(6,2),
    BREADTH_RATIO          NUMBER(8,4),
    NET_ADVANCES           NUMBER(6,0),
    AVG_MARKET_RETURN_PCT  NUMBER(8,4),
    REGIME_DURATION_DAYS   NUMBER(6,0),
    CONSTRAINT PK_MARKET_REGIMES PRIMARY KEY (DATETIME)
);
