-- Oracle DDL Script for Stage 3.5 Theme Engine Tables

CREATE TABLE STAGING.THEME_MASTER (
    THEME_CODE          VARCHAR2(50) NOT NULL,
    THEME_NAME          VARCHAR2(100) NOT NULL,
    DESCRIPTION         VARCHAR2(255),
    STOCK_COUNT         NUMBER(4,0) DEFAULT 0,
    CONSTRAINT PK_THEME_MASTER PRIMARY KEY (THEME_CODE)
);

CREATE TABLE STAGING.THEME_CONSTITUENTS (
    THEME_CODE          VARCHAR2(50) NOT NULL,
    SYMBOL              VARCHAR2(30) NOT NULL,
    WEIGHT              NUMBER(5,2) DEFAULT 1.0,
    CONSTRAINT PK_THEME_CONSTITUENTS PRIMARY KEY (THEME_CODE, SYMBOL)
);

CREATE TABLE STAGING.THEME_DAILY (
    THEME_CODE          VARCHAR2(50) NOT NULL,
    DATETIME            DATE NOT NULL,
    AVG_CHANGE_PCT      NUMBER(8,4),
    MEDIAN_CHANGE_PCT   NUMBER(8,4),
    TOTAL_VOLUME        NUMBER(15,0),
    AVG_RSI_14          NUMBER(8,4),
    ACTIVE_STOCKS       NUMBER(6,0),
    ADVANCING_STOCKS    NUMBER(6,0),
    DECLINING_STOCKS    NUMBER(6,0),
    UNCHANGED_STOCKS    NUMBER(6,0),
    BREADTH_RATIO       NUMBER(8,4),
    NET_ADVANCES        NUMBER(6,0),
    PCT_ABOVE_EMA20     NUMBER(6,2),
    PCT_ABOVE_EMA50     NUMBER(6,2),
    PCT_ABOVE_EMA200    NUMBER(6,2),
    CONSTRAINT PK_THEME_DAILY PRIMARY KEY (THEME_CODE, DATETIME)
);

CREATE TABLE STAGING.THEME_ROTATION (
    THEME_CODE             VARCHAR2(50) NOT NULL,
    DATETIME               DATE NOT NULL,
    RETURN_1M              NUMBER(8,4),
    RETURN_3M              NUMBER(8,4),
    RETURN_6M              NUMBER(8,4),
    RETURN_12M             NUMBER(8,4),
    RELATIVE_STRENGTH_1M   NUMBER(8,4),
    RELATIVE_STRENGTH_3M   NUMBER(8,4),
    RELATIVE_STRENGTH_6M   NUMBER(8,4),
    RELATIVE_STRENGTH_12M  NUMBER(8,4),
    THEME_RANK_3M          NUMBER(4,0),
    RANK_DELTA_3M          NUMBER(4,0),
    ROTATION_STATUS        VARCHAR2(20),
    CONSTRAINT PK_THEME_ROTATION PRIMARY KEY (THEME_CODE, DATETIME)
);
