-- Oracle DDL Script for Stage 3.3 Rotation Engine Tables

-- 1. Sector Rotation Table
-- DROP TABLE STAGING.SECTOR_ROTATION CASCADE CONSTRAINTS;

CREATE TABLE STAGING.SECTOR_ROTATION (
    SECTOR_CODE            VARCHAR2(50) NOT NULL,
    DATETIME               DATE NOT NULL,
    RETURN_1M              NUMBER(8,4),
    RETURN_3M              NUMBER(8,4),
    RETURN_6M              NUMBER(8,4),
    RETURN_12M             NUMBER(8,4),
    RELATIVE_STRENGTH_1M   NUMBER(8,4),
    RELATIVE_STRENGTH_3M   NUMBER(8,4),
    RELATIVE_STRENGTH_6M   NUMBER(8,4),
    RELATIVE_STRENGTH_12M  NUMBER(8,4),
    SECTOR_RANK_1M         NUMBER(4,0),
    SECTOR_RANK_3M         NUMBER(4,0),
    SECTOR_RANK_12M        NUMBER(4,0),
    RANK_DELTA_3M          NUMBER(4,0),
    ROTATION_STATUS        VARCHAR2(20),
    CONSTRAINT PK_SECTOR_ROTATION PRIMARY KEY (SECTOR_CODE, DATETIME)
);

-- 2. Industry Rotation Table
-- DROP TABLE STAGING.INDUSTRY_ROTATION CASCADE CONSTRAINTS;

CREATE TABLE STAGING.INDUSTRY_ROTATION (
    INDUSTRY_CODE          VARCHAR2(100) NOT NULL,
    DATETIME               DATE NOT NULL,
    RETURN_1M              NUMBER(8,4),
    RETURN_3M              NUMBER(8,4),
    RETURN_6M              NUMBER(8,4),
    RETURN_12M             NUMBER(8,4),
    RELATIVE_STRENGTH_1M   NUMBER(8,4),
    RELATIVE_STRENGTH_3M   NUMBER(8,4),
    RELATIVE_STRENGTH_6M   NUMBER(8,4),
    RELATIVE_STRENGTH_12M  NUMBER(8,4),
    INDUSTRY_RANK_1M       NUMBER(4,0),
    INDUSTRY_RANK_3M       NUMBER(4,0),
    INDUSTRY_RANK_12M      NUMBER(4,0),
    RANK_DELTA_3M          NUMBER(4,0),
    ROTATION_STATUS        VARCHAR2(20),
    CONSTRAINT PK_INDUSTRY_ROTATION PRIMARY KEY (INDUSTRY_CODE, DATETIME)
);
