-- Oracle DDL Script for Stage 3.1 Market Structure Foundation Tables
-- Execute in Oracle 23c XE under schemas MASTER and ANALYSIS

-- 1. Master Tables
-- DROP TABLE MASTER.INDUSTRY_MASTER CASCADE CONSTRAINTS;
-- DROP TABLE MASTER.SECTOR_MASTER CASCADE CONSTRAINTS;

CREATE TABLE MASTER.SECTOR_MASTER (
    SECTOR_CODE      VARCHAR2(50) NOT NULL,
    SECTOR_NAME      VARCHAR2(100) NOT NULL,
    STOCK_COUNT      NUMBER(6,0),
    TOTAL_MARKET_CAP NUMBER(20,2),
    CREATED_AT       DATE DEFAULT SYSDATE,
    CONSTRAINT PK_SECTOR_MASTER PRIMARY KEY (SECTOR_CODE)
);

CREATE TABLE MASTER.INDUSTRY_MASTER (
    INDUSTRY_CODE    VARCHAR2(100) NOT NULL,
    INDUSTRY_NAME    VARCHAR2(150) NOT NULL,
    SECTOR_CODE      VARCHAR2(50) NOT NULL,
    STOCK_COUNT      NUMBER(6,0),
    TOTAL_MARKET_CAP NUMBER(20,2),
    CREATED_AT       DATE DEFAULT SYSDATE,
    CONSTRAINT PK_INDUSTRY_MASTER PRIMARY KEY (INDUSTRY_CODE),
    CONSTRAINT FK_IND_SECTOR FOREIGN KEY (SECTOR_CODE) REFERENCES MASTER.SECTOR_MASTER(SECTOR_CODE)
);

-- 2. Daily Aggregation Tables
-- DROP TABLE ANALYSIS.SECTOR_DAILY CASCADE CONSTRAINTS;
-- DROP TABLE ANALYSIS.INDUSTRY_DAILY CASCADE CONSTRAINTS;

CREATE TABLE ANALYSIS.SECTOR_DAILY (
    SECTOR_CODE       VARCHAR2(50) NOT NULL,
    DATETIME          DATE NOT NULL,
    AVG_CHANGE_PCT    NUMBER(8,4),
    MEDIAN_CHANGE_PCT NUMBER(8,4),
    TOTAL_VOLUME      NUMBER(20,0),
    AVG_RSI_14        NUMBER(8,4),
    ACTIVE_STOCKS     NUMBER(6,0),
    CONSTRAINT PK_SECTOR_DAILY PRIMARY KEY (SECTOR_CODE, DATETIME)
);

CREATE TABLE ANALYSIS.INDUSTRY_DAILY (
    INDUSTRY_CODE     VARCHAR2(100) NOT NULL,
    DATETIME          DATE NOT NULL,
    AVG_CHANGE_PCT    NUMBER(8,4),
    MEDIAN_CHANGE_PCT NUMBER(8,4),
    TOTAL_VOLUME      NUMBER(20,0),
    AVG_RSI_14        NUMBER(8,4),
    ACTIVE_STOCKS     NUMBER(6,0),
    CONSTRAINT PK_INDUSTRY_DAILY PRIMARY KEY (INDUSTRY_CODE, DATETIME)
);

-- 3. Performance Summary Tables
-- DROP TABLE ANALYSIS.SECTOR_PERFORMANCE CASCADE CONSTRAINTS;
-- DROP TABLE ANALYSIS.INDUSTRY_PERFORMANCE CASCADE CONSTRAINTS;

CREATE TABLE ANALYSIS.SECTOR_PERFORMANCE (
    SECTOR_CODE       VARCHAR2(50) NOT NULL,
    PERIOD_TYPE       VARCHAR2(20) NOT NULL,
    PERIOD_LABEL      VARCHAR2(20) NOT NULL,
    AVG_RETURN_PCT    NUMBER(12,4),
    CAGR_PCT          NUMBER(12,4),
    WIN_RATE_PCT      NUMBER(8,4),
    VOLATILITY_PCT    NUMBER(12,4),
    MAX_DRAWDOWN_PCT  NUMBER(12,4),
    SAMPLE_COUNT      NUMBER(6,0),
    CONSTRAINT PK_SECTOR_PERFORMANCE PRIMARY KEY (SECTOR_CODE, PERIOD_TYPE, PERIOD_LABEL)
);

CREATE TABLE ANALYSIS.INDUSTRY_PERFORMANCE (
    INDUSTRY_CODE     VARCHAR2(100) NOT NULL,
    PERIOD_TYPE       VARCHAR2(20) NOT NULL,
    PERIOD_LABEL      VARCHAR2(20) NOT NULL,
    AVG_RETURN_PCT    NUMBER(12,4),
    CAGR_PCT          NUMBER(12,4),
    WIN_RATE_PCT      NUMBER(8,4),
    VOLATILITY_PCT    NUMBER(12,4),
    MAX_DRAWDOWN_PCT  NUMBER(12,4),
    SAMPLE_COUNT      NUMBER(6,0),
    CONSTRAINT PK_INDUSTRY_PERFORMANCE PRIMARY KEY (INDUSTRY_CODE, PERIOD_TYPE, PERIOD_LABEL)
);
