-- Oracle DDL Script for STAGING.RAW_STOCK_HISTORY
-- Stores raw un-processed OHLCV data fetched directly from Fyers / CSVs

-- DROP TABLE "STAGING"."RAW_STOCK_HISTORY" CASCADE CONSTRAINTS;

CREATE TABLE "STAGING"."RAW_STOCK_HISTORY" 
(
    "SYMBOL"     VARCHAR2(50) NOT NULL, 
    "DATETIME"   DATE NOT NULL, 
    "OPEN"       NUMBER(12,4), 
    "HIGH"       NUMBER(12,4), 
    "LOW"        NUMBER(12,4), 
    "CLOSE"      NUMBER(12,4), 
    "VOLUME"     NUMBER(15,0),
    "CREATED_AT" DATE DEFAULT SYSDATE,
    CONSTRAINT "PK_RAW_STOCK_HISTORY" PRIMARY KEY ("SYMBOL", "DATETIME")
);
