-- Oracle DDL Script for Stage 3.2 Breadth Engine Tables & Alterations

-- 1. Market-Wide Daily Breadth Table
-- DROP TABLE STAGING.MARKET_BREADTH_DAILY CASCADE CONSTRAINTS;

CREATE TABLE STAGING.MARKET_BREADTH_DAILY (
    DATETIME            DATE NOT NULL,
    TOTAL_STOCKS        NUMBER(6,0),
    ADVANCING_STOCKS    NUMBER(6,0),
    DECLINING_STOCKS    NUMBER(6,0),
    UNCHANGED_STOCKS    NUMBER(6,0),
    BREADTH_RATIO       NUMBER(8,4),
    NET_ADVANCES        NUMBER(6,0),
    PCT_ABOVE_EMA20     NUMBER(8,4),
    PCT_ABOVE_EMA50     NUMBER(8,4),
    PCT_ABOVE_EMA200    NUMBER(8,4),
    CONSTRAINT PK_MARKET_BREADTH_DAILY PRIMARY KEY (DATETIME)
);

-- 2. Alter SECTOR_DAILY to add breadth columns (if not already present)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE STAGING.SECTOR_DAILY ADD (
        ADVANCING_STOCKS NUMBER(6,0),
        DECLINING_STOCKS NUMBER(6,0),
        UNCHANGED_STOCKS NUMBER(6,0),
        BREADTH_RATIO    NUMBER(8,4),
        NET_ADVANCES     NUMBER(6,0),
        PCT_ABOVE_EMA20  NUMBER(8,4),
        PCT_ABOVE_EMA50  NUMBER(8,4),
        PCT_ABOVE_EMA200 NUMBER(8,4)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF; -- ignore column already exists
END;
/

-- 3. Alter INDUSTRY_DAILY to add breadth columns (if not already present)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE STAGING.INDUSTRY_DAILY ADD (
        ADVANCING_STOCKS NUMBER(6,0),
        DECLINING_STOCKS NUMBER(6,0),
        UNCHANGED_STOCKS NUMBER(6,0),
        BREADTH_RATIO    NUMBER(8,4),
        NET_ADVANCES     NUMBER(6,0),
        PCT_ABOVE_EMA20  NUMBER(8,4),
        PCT_ABOVE_EMA50  NUMBER(8,4),
        PCT_ABOVE_EMA200 NUMBER(8,4)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF; -- ignore column already exists
END;
/
