-- Oracle DDL Script for Stage 3.4 Stock Ranking Engine Tables

-- Stock Rankings Table
-- DROP TABLE STAGING.STOCK_RANKINGS CASCADE CONSTRAINTS;

CREATE TABLE STAGING.STOCK_RANKINGS (
    SYMBOL               VARCHAR2(30) NOT NULL,
    DATETIME             DATE NOT NULL,
    SECTOR_CODE          VARCHAR2(50),
    INDUSTRY_CODE        VARCHAR2(100),
    RETURN_3M            NUMBER(8,4),
    SECTOR_RANK          NUMBER(6,0),
    INDUSTRY_RANK        NUMBER(6,0),
    MARKET_RANK          NUMBER(6,0),
    SECTOR_PERCENTILE    NUMBER(6,2),
    INDUSTRY_PERCENTILE  NUMBER(6,2),
    MARKET_PERCENTILE    NUMBER(6,2),
    RSI_RANK_INDUSTRY    NUMBER(6,0),
    CONSTRAINT PK_STOCK_RANKINGS PRIMARY KEY (SYMBOL, DATETIME)
);
