-- Oracle DDL Script for HMIE v1.1.0 (Stage 4: Historical Evidence Engine)

CREATE TABLE STAGING.EVIDENCE_CORRECTIONS (
    EVENT_ID               NUMBER(6,0) PRIMARY KEY,
    EVENT_NAME             VARCHAR2(80) NOT NULL,
    PEAK_DATE              DATE NOT NULL,
    TROUGH_DATE            DATE NOT NULL,
    RECOVERY_DATE          DATE,
    MAX_DRAWDOWN_PCT       NUMBER(6,2),
    CORRECTION_DAYS        NUMBER(6,0),
    RECOVERY_DAYS          NUMBER(6,0),
    RECOVERY_TYPE          VARCHAR2(30), -- V_SHAPED, U_SHAPED, L_SHAPED_CONSOLIDATION
    TOP_SECTOR_30D         VARCHAR2(50),
    TOP_SECTOR_60D         VARCHAR2(50),
    TOP_THEME_60D          VARCHAR2(50)
);

CREATE TABLE STAGING.EVIDENCE_MACRO_EVENTS (
    EVENT_ID               NUMBER(6,0) PRIMARY KEY,
    EVENT_NAME             VARCHAR2(100) NOT NULL,
    EVENT_CATEGORY         VARCHAR2(30) NOT NULL, -- BUDGET, ELECTION, CRISIS, SEASONALITY
    EVENT_DATE             DATE NOT NULL,
    REGIME_AT_EVENT        VARCHAR2(30),
    PRE_30D_MARKET_RETURN  NUMBER(6,2),
    POST_30D_MARKET_RETURN NUMBER(6,2),
    TOP_SECTOR_POST_30D    VARCHAR2(50),
    TOP_THEME_POST_30D     VARCHAR2(50)
);
